language: rust

before_install:
  - git clone https://github.com/eldruin/rust-driver-example-ci-scripts ci
  - bash ci/before_install.sh

env:
  global:
    - TARGET=thumbv6m-none-eabi # nRF51822

rust:
  - stable
  - nightly
  - 1.31.0 # Minimum Supported Rust Version

install:
  bash ci/install.sh

script:
  bash ci/script.sh

after_script: set +e

cache: cargo
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  bash ci/before_cache.sh

notifications:
  email:
    on_success: never
